name: Build and Deploy FastAPI to ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and Push Docker Image to ACR
        run: |
          az acr login --name ${{ vars.ACR_NAME }}
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/fastapi-app:latest .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/fastapi-app:latest

      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --name ${{ vars.ACI_NAME }} \
            --image ${{ vars.ACR_NAME }}.azurecr.io/fastapi-app:latest \
            --registry-login-server ${{ vars.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.AZURE_CLIENT_ID }} \
            --registry-password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --dns-name-label myfastapi1112 \
            --ports 80 \
            --restart-policy Never || \
          az container update \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --name ${{ vars.ACI_NAME }} \
            --image ${{ vars.ACR_NAME }}.azurecr.io/fastapi-app:latest

